server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
servlet:
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wxthxy.market.entity
