server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wxthxy.market.entity
